### ISSUE TITLE
Error loading syntax: "Capture number is greater than the number of captures in the regex"

### ISSUE THREAD

**Issue by gredman** [dan-c-underwood/Arm.novaextension#1]
Hi, Nova 7.5 is failing to load this syntax definition with the following error:
```
Error loading syntax “Arm.xml”

Capture number is greater than the number of captures in the regex: 3, unknown, <SKRegularExpression: 0x6000005a7e40> { pattern=\b(?i)(?:mov(?:w|t)?|pac(?:dz?[a|b]|ga|i(?:[a|b](?:1716|sp|z)?)|z[a|b])|swi|svc|wfi|dmb|clrex|dsb|isb|v?(?:push|pop)|b(?:l|l?x|l?r)?|(?:i|e)?ret(?:aa|ab)?|(?:st|ld)(?:p|r(?:ex|s?(?:h|b)|d)?|m(?:(?:f|e)(?:d|a)|(?:d|i)(?:b|a))?))(?:(?:(?=s)s(\w{2})?)|(\w{2})s?)?(?-i)\b, options=82 }, {92, 23}
```

The capture in question is part of scope `arm.keyword.mnenomic.memory`.

Thanks!

**Comment by dan-c-underwood** [comment]
Sorry for the delay in getting back to you on this. This should now be fixed in 1.1.2 😄 I had spotted that the extension wasn't loading - but wasn't getting any errors flagging it. Where did the error message appear for you?

**Comment by gredman** [comment]
Not a problem, thanks for taking the time to fix it.

As for the error message, I believe it was showing the Extension Console.

**Comment by dan-c-underwood** [comment]
Thanks - that's useful to know, for some reason it wasn't showing up on on my side!
